### ISSUE TITLE
get optimal route

### ISSUE THREAD

**Issue by levg34** [levg34/chessq#2]
Calculate optimal route(s) between the two points (Route the shortest possible)

**Comment by madblade** [comment]
Dijkstra, BFS or O(1) solutions are mentioned here: 
http://stackoverflow.com/questions/2339101/knights-shortest-path-chess-question

More doc here: 
https://github.com/Jarosh/Exercises/wiki/Finding-the-shortest-path-as-for-knight--in-the-game-of-chess-on-an-infinite-board

**Comment by levg34** [comment]
fix #1 and fix #21 if closed

**Comment by levg34** [comment]
not working
